# Generated by Django 3.0.6 on 2020-05-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craiglistclone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'searches'},
        ),
    ]
